import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';

import { AppComponent } from './app.component';
import { MyComponentComponent } from './my-component/my-component.component';

/*
service generated by command "ng g service <name of service>"
manually import service */
import { MyDataService } from './my-data.service';


/*
Install animation using "npm install @angulat/animation@latest --save"
Manually add following reference
*/
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';


@NgModule({
  declarations: [
    AppComponent,
    MyComponentComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
BrowserAnimationsModule
  ],
  /*manually add provider  */
  providers: [MyDataService],
  bootstrap: [AppComponent]
})
export class AppModule { }
